### ISSUE TITLE
报错 throw new Error("请输入文件全称，带上后缀")

### ISSUE THREAD

**Issue by guchengfeng** [LiuC520/nodediffpatch#3]
/Users/guchengfeng/nodediffpatch/patbundle:61
            throw new Error("请输入文件全称，带上后缀")
            ^

Error: 请输入文件全称，带上后缀
    at /Users/guchengfeng/nodediffpatch/patbundle:61:19
    at suppressedCallback (fs.js:202:5)
    at FSReqCallback.oncomplete (fs.js:146:23)

**Comment by chenzhengxu** [comment]
碰到了类似的问题，原因是代码中固定拼接了`patch`路径

```javascript
var oldFilePath = currentpath + '/patch/' + o;
var newFilePath = currentpath + '/patch/' + n;
```
https://github.com/LiuC520/nodediffpatch/blob/master/patbundle#L54-L55

解决方式是在当前目录新建patch目录，并把old和new文件放入
